import { SceneSpec } from './types';

export const sampleScene: SceneSpec = {
  id: 'scene-1',
  entities: {
    e1: { id: 'e1', x: 220, y: 140, width: 28, height: 20 },
    e2: { id: 'e2', x: 268, y: 140, width: 28, height: 20 },
    e3: { id: 'e3', x: 316, y: 140, width: 28, height: 20 },
    e4: { id: 'e4', x: 364, y: 140, width: 28, height: 20 },
    e5: { id: 'e5', x: 412, y: 140, width: 28, height: 20 },
    e6: { id: 'e6', x: 220, y: 180, width: 28, height: 20 },
    e7: { id: 'e7', x: 268, y: 180, width: 28, height: 20 },
    e8: { id: 'e8', x: 316, y: 180, width: 28, height: 20 },
    e9: { id: 'e9', x: 364, y: 180, width: 28, height: 20 },
    e10: { id: 'e10', x: 412, y: 180, width: 28, height: 20 },
    e11: { id: 'e11', x: 220, y: 220, width: 28, height: 20 },
    e12: { id: 'e12', x: 268, y: 220, width: 28, height: 20 },
    e13: { id: 'e13', x: 316, y: 220, width: 28, height: 20 },
    e14: { id: 'e14', x: 364, y: 220, width: 28, height: 20 },
    e15: { id: 'e15', x: 412, y: 220, width: 28, height: 20 },
  },
  groups: {
    'g-enemies': {
      id: 'g-enemies',
      members: [
        'e1',
        'e2',
        'e3',
        'e4',
        'e5',
        'e6',
        'e7',
        'e8',
        'e9',
        'e10',
        'e11',
        'e12',
        'e13',
        'e14',
        'e15',
      ],
    },
  },
  behaviors: {
    'b-formation': {
      id: 'b-formation',
      name: 'Formation Patrol',
      target: { type: 'group', groupId: 'g-enemies' },
      rootActionId: 'a-root',
    },
  },
  actions: {
    'a-root': { id: 'a-root', type: 'Repeat', name: 'Loop', childId: 'a-seq' },
    'a-seq': {
      id: 'a-seq',
      type: 'Sequence',
      name: 'Sweep + Drop',
      children: ['a-move-right', 'a-drop-right', 'a-wait-right', 'a-move-left', 'a-drop-left', 'a-wait-left'],
    },
    'a-move-right': {
      id: 'a-move-right',
      type: 'MoveUntil',
      name: 'Move Right',
      target: { type: 'group', groupId: 'g-enemies' },
      velocity: { x: 80, y: 0 },
      conditionId: 'c-bounds',
    },
    'a-move-left': {
      id: 'a-move-left',
      type: 'MoveUntil',
      name: 'Move Left',
      target: { type: 'group', groupId: 'g-enemies' },
      velocity: { x: -80, y: 0 },
      conditionId: 'c-bounds',
    },
    'a-drop-right': {
      id: 'a-drop-right',
      type: 'Call',
      name: 'Drop',
      callId: 'drop',
      target: { type: 'group', groupId: 'g-enemies' },
      args: { dy: 24 },
    },
    'a-drop-left': {
      id: 'a-drop-left',
      type: 'Call',
      name: 'Drop',
      callId: 'drop',
      target: { type: 'group', groupId: 'g-enemies' },
      args: { dy: 24 },
    },
    'a-wait-right': { id: 'a-wait-right', type: 'Wait', name: 'Pause', durationMs: 150 },
    'a-wait-left': { id: 'a-wait-left', type: 'Wait', name: 'Pause', durationMs: 150 },
  },
  conditions: {
    'c-bounds': {
      id: 'c-bounds',
      type: 'BoundsHit',
      bounds: { minX: 80, maxX: 944, minY: 60, maxY: 720 },
      mode: 'any',
    },
  },
};
