import { arrangeGrid } from './formation';
import { SceneSpec } from './types';

const enemyEntities = arrangeGrid(
  undefined,
  {
    rows: 3,
    cols: 5,
    startX: 220,
    startY: 140,
    spacingX: 48,
    spacingY: 40,
    factory: (index) => ({
      id: `e${index + 1}`,
      x: 0,
      y: 0,
      width: 28,
      height: 20,
      scaleX: 1,
      scaleY: 1,
      originX: 0.5,
      originY: 0.5,
      alpha: 1,
      visible: true,
      depth: 0,
      flipX: false,
      flipY: false,
      rotationDeg: 0,
    }),
  }
);

const entities = Object.fromEntries(enemyEntities.map((entity) => [entity.id, entity]));
const enemyIds = enemyEntities.map((entity) => entity.id);

export const sampleScene: SceneSpec = {
  id: 'scene-1',
  world: {
    width: 1024,
    height: 768,
  },
  entities,
  groups: {
    'g-enemies': {
      id: 'g-enemies',
      name: 'Enemy Formation',
      members: enemyIds,
      layout: {
        type: 'grid',
        rows: 3,
        cols: 5,
        startX: 220,
        startY: 140,
        spacingX: 48,
        spacingY: 40,
      },
    },
  },
  attachments: {
    'att-loop': {
      id: 'att-loop',
      name: 'Loop',
      order: 0,
      target: { type: 'group', groupId: 'g-enemies' },
      applyTo: 'group',
      enabled: true,
      presetId: 'Repeat',
    },
    'att-move-right': {
      id: 'att-move-right',
      name: 'Move Right',
      order: 1,
      target: { type: 'group', groupId: 'g-enemies' },
      applyTo: 'group',
      enabled: true,
      presetId: 'MoveUntil',
      params: { velocityX: 80, velocityY: 0 },
      condition: {
        type: 'BoundsHit',
        bounds: { minX: 80, maxX: 944, minY: 60, maxY: 720 },
        mode: 'any',
        scope: 'group-extents',
        behavior: 'limit',
      },
    },
    'att-drop-right': {
      id: 'att-drop-right',
      name: 'Drop',
      order: 2,
      target: { type: 'group', groupId: 'g-enemies' },
      applyTo: 'group',
      enabled: true,
      presetId: 'Call',
      params: { callId: 'drop', dy: 24 },
    },
    'att-wait-right': {
      id: 'att-wait-right',
      name: 'Pause',
      order: 3,
      target: { type: 'group', groupId: 'g-enemies' },
      applyTo: 'group',
      enabled: true,
      presetId: 'Wait',
      params: { durationMs: 150 },
    },
    'att-move-left': {
      id: 'att-move-left',
      name: 'Move Left',
      order: 4,
      target: { type: 'group', groupId: 'g-enemies' },
      applyTo: 'group',
      enabled: true,
      presetId: 'MoveUntil',
      params: { velocityX: -80, velocityY: 0 },
      condition: {
        type: 'BoundsHit',
        bounds: { minX: 80, maxX: 944, minY: 60, maxY: 720 },
        mode: 'any',
        scope: 'group-extents',
        behavior: 'limit',
      },
    },
    'att-drop-left': {
      id: 'att-drop-left',
      name: 'Drop',
      order: 5,
      target: { type: 'group', groupId: 'g-enemies' },
      applyTo: 'group',
      enabled: true,
      presetId: 'Call',
      params: { callId: 'drop', dy: 24 },
    },
    'att-wait-left': {
      id: 'att-wait-left',
      name: 'Pause',
      order: 6,
      target: { type: 'group', groupId: 'g-enemies' },
      applyTo: 'group',
      enabled: true,
      presetId: 'Wait',
      params: { durationMs: 150 },
    },
  },
  behaviors: {},
  actions: {},
  conditions: {},
};
