name: PhaserActions CI

on:
  push:
    branches:
      - main
      - master
  pull_request:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

permissions:
  contents: read

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: npm

      - name: Install
        run: npm ci

      - name: Install Playwright Browser
        run: npx playwright install --with-deps chromium

      - name: Unit Tests
        run: npm run test:unit

      - name: E2E Tests
        run: npm run test:e2e

      - name: Build
        run: npm run build
